In [1]:
import pandas as pd
import numpy as np

Untuk data training model bert sebagai aspect extractor, data review tokopedia yang sudah dilabel akan diubah menjadi berikut:
- Review (text)
- Pelayanan (boolean)
- Pengiriman (boolean)
- Barang (boolean)

In [2]:
df = pd.read_csv('tokopedia_review - tokopedia_review.csv')
df.head()

review  rating  pelayanan   
0  admin slow respon banget.. pengiriman lama ban...       1        0.0  \
1          Pelayanan penjual kurang, Pengiriman lama       1        0.0   
2                               tv rusak ya kedip ya       1        NaN   
3  jijik banget pelayanan disini, dari awal chatt...       1        0.0   
4          terlalu lama pengirimannya hampir 1 bulan       1        NaN   

   pengiriman  barang  Unnamed: 5   
0         0.0     NaN         NaN  \
1         0.0     NaN         NaN   
2         NaN     0.0         NaN   
3         0.0     NaN         NaN   
4         0.0     NaN         NaN   

                                          Unnamed: 6  Unnamed: 7 Unnamed: 8  
0                                                NaN         NaN        NaN  
1                                             review      aspect   sentimen  
2  admin slow respon banget.. pengiriman lama ban...   pelayanan          0  
3  admin slow respon banget.. pengiriman lama ban...  pengiriman          0  
4                                                NaN         NaN        NaN

In [3]:
df = df.drop(df.columns[5:], axis=1)
df.head()

review  rating  pelayanan   
0  admin slow respon banget.. pengiriman lama ban...       1        0.0  \
1          Pelayanan penjual kurang, Pengiriman lama       1        0.0   
2                               tv rusak ya kedip ya       1        NaN   
3  jijik banget pelayanan disini, dari awal chatt...       1        0.0   
4          terlalu lama pengirimannya hampir 1 bulan       1        NaN   

   pengiriman  barang  
0         0.0     NaN  
1         0.0     NaN  
2         NaN     0.0  
3         0.0     NaN  
4         0.0     NaN

In [5]:
df.shape

(5466, 5)

In [7]:
df[~(df['pelayanan'].isnull() & df['pengiriman'].isnull() & df['barang'].isnull())].shape

(3618, 5)

In [8]:
df = df.dropna(axis=0, how='all', subset=['pelayanan', 'pengiriman', 'barang'])

In [9]:
df['pelayanan'].unique()

array([ 0., nan,  2.,  1.])

In [10]:
df['pengiriman'].unique()

array([ 0., nan,  1.,  2.])

In [11]:
df['barang'].unique()

array([nan,  0.,  2.,  1.])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3618 entries, 0 to 3625
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   review      3618 non-null   object 
 1   rating      3618 non-null   int64  
 2   pelayanan   1051 non-null   float64
 3   pengiriman  1519 non-null   float64
 4   barang      3194 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 169.6+ KB


In [13]:
print(f"Pelayanan: {sum(~df['pelayanan'].isna())}")
print(f"Pengiriman: {sum(~df['pengiriman'].isna())}")
print(f"Barang: {sum(~df['barang'].isna())}")

Pelayanan: 1051
Pengiriman: 1519
Barang: 3194


In [14]:
df['pelayanan'] = ~df['pelayanan'].isna()
df['pengiriman'] = ~df['pengiriman'].isna()
df['barang'] = ~df['barang'].isna()

In [15]:
df.head()

review  rating  pelayanan   
0  admin slow respon banget.. pengiriman lama ban...       1       True  \
1          Pelayanan penjual kurang, Pengiriman lama       1       True   
2                               tv rusak ya kedip ya       1      False   
3  jijik banget pelayanan disini, dari awal chatt...       1       True   
4          terlalu lama pengirimannya hampir 1 bulan       1      False   

   pengiriman  barang  
0        True   False  
1        True   False  
2       False    True  
3        True   False  
4        True   False

In [18]:
df.shape

(3618, 5)

In [17]:
df.to_csv('aspect.csv', index=False)

In [19]:
df.tail(10)

review  rating  pelayanan   
3616                bahannya tebel, mudah2an nyerap air       5      False  \
3617          kualitas barang cukup baik sesuai harapan       5      False   
3618                                barang lumayan baik       5      False   
3619  Bahan material bagus, ukuran sedang, desain me...       5      False   
3620                                       Produknya ok       5      False   
3621                                   sesuai deskripsi       5      False   
3622           bagus... barang sesuai dengan deskripsi.       5      False   
3623                       Murah meriah...berkualitas..       5      False   
3624  depan pintu kamar mandi kering. menyerap bange...       5      False   
3625                         Kualitas barang bermasalah       1      False   

      pengiriman  barang  
3616       False    True  
3617       False    True  
3618       False    True  
3619       False    True  
3620       False    True  
3621       False    True  
3622       False    True  
3623       False    True  
3624       False    True  
3625       False    True